### ISSUE TITLE
Using with Typescript

### ISSUE THREAD

**Issue by guillaumepn** [stems/graphql-depth-limit#8]
I'm having trouble making this package work with TypeScript (I'm using Apollo Server with apollo-server-express)

I installed `graphql-depth-limit` along with `@types/graphql-depth-limit` by @eritikass 

Here is what I did : 

```javascript
import depthLimit from "graphql-depth-limit";

const server = new ApolloServer({
    typeDefs,
    resolvers,
    validationRules: [depthLimit(10)],
    context: ({ req }: any) => ({ req })
});
```

But I'm getting the following error : 
`TypeError: graphql_depth_limit_1.default is not a function`

As the code I used is pretty simple, I would guess the problem could come from the TS definitions. I'm not an expert but they seem fine :  

```javascript
declare function depthLimit(depthLimit: number, options?: depthLimit.Options, callback?: (obj: any) => void): any;
export = depthLimit;

declare namespace depthLimit {
    interface Options {
        ignore: Array<string | RegExp | ((queryDepths: any[]) => boolean)>;
    }
}
```

Did anyone manage to make this package work with TS ? 

Thanks!

**Comment by snnsnn** [comment]
`default is not a function` error usually associated with node and ES6 module incompatibility. 
Try `import * as depthLimit from "graphql-depth-limit";`

**Comment by guillaumepn** [comment]
Thanks, that solved it!
